{"stats": {"errors": 1, "failures": 0, "passes": 0, "skipped": 0, "encoding": "UTF-8", "total": 1}, "results": [{"classname": "index_test:TxTest", "name": "test_verify_input", "time": 0.0008740425109863281, "type": "error", "errtype": "builtins.NameError", "message": "name 'tx' is not defined", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/5AUsK0H7q2C/tx-verifying-input-jsong-pb-sf-072618/test/index_test.py\", line 10, in test_verify_input\n    self.assertTrue(tx.verify_input(0))\n  File \"/home/5AUsK0H7q2C/tx-verifying-input-jsong-pb-sf-072618/index.ipynb\", line 32, in verify_input\n    \"    def verify_input(self, input_index):\\n\",\nNameError: name 'tx' is not defined\n"}]}